### PR TITLE
Add ppc64le build

### PR DESCRIPTION
**Pull request by runlevel5**
## Changes

* Add ppc64le build

### CODE REVIEW

**Comment by runlevel5** [comment]
cc @Spasi the PR is ready for review

**Comment by Spasi** [comment]
Hey @runlevel5,

We use a container image for the build, instead of building directly on `ubuntu-latest`, to maintain broader compatibility with old GLIBC versions. Ubuntu 18.04 corresponds to GLIBC 2.27. If we build on anything newer, a lot of relatively recent Linux distributions won't be able to run LWJGL.

I'm not sure if or why ppc64le needs 22.04, but I cannot merge this PR as is.

**Comment by runlevel5** [comment]
👋 @Spasi 

Firstly great thanks for reviewing my work.

We need Ubuntu 22.04 because we need ppc64le cross-compilation support (specifically the `gcc-powerpc64le-linux-gnu` and  `g++-powerpc64le-linux-gnu`).

I do not think there is any easy way to get ppc64le cross compilation support with Ubuntu 18.04 unless we maintain a set of custom DEB packages for `gcc-powerpc64le-*` which IMHO is too much overhead.

So since we are already using container, I would like to propose that we adopt [docker/buildx](https://github.com/docker/setup-buildx-action/). This action would launch QEMU at the background to compile the code natively on the VM instead of cross-compilation. Thought?

**Comment by Spasi** [comment]
I've read that QEMU builds are very slow on Github Actions. Not sure if it's worth the trouble, but you're welcome to try.

Btw, I'm worried about ppc64le in general. Whenever I read about it, it sounds like a dead architecture. Are there markets where modern PowerPC hardware is still being sold and used? What for exactly? Why are ppc64le users interested in LWJGL? (please don't say to play Minecraft)

This is the same concern I have with people asking for LWJGL on BSD systems. I'm not saying there aren't any real users and interesting use cases, but please understand that each new platform/architecture we add to LWJGL means so much extra maintenance burden. As long as I'm doing this solo, it's very hard to justify that burden.

**Comment by runlevel5** [comment]
> We need Ubuntu 22.04 because we need ppc64le cross-compilation support (specifically the gcc-powerpc64le-linux-gnu and g++-powerpc64le-linux-gnu).`

it turns out 18.04 does have those packages and I was wrong. I've pushed the amendment

> Btw, I'm worried about ppc64le in general. Whenever I read about it, it sounds like a dead architecture. Are there markets where modern PowerPC hardware is still being sold and used? What for exactly? Why are ppc64le users interested in LWJGL? (please don't say to play Minecraft)

OpenPOWER architecture is pretty much alive. In fact 9/10 enterprises like banks, institutions (and many other fields) are still using it. If you are interested in PowerPC hardware, please have a look at Raptor Computing System Blackbird or Talos II (and I have not even mentioned about the wide range of hardware offerings from IBM and other OpenPOWER vendors). LWJGL are and have been utilised in many applications and games, I cannot answer for everyone in the community but I know my professor is utilising the OpenCL binding.

**Comment by runlevel5** [comment]
@Spasi please give this PR another round of review. Many thanks

**Comment by Spasi** [comment]
Merged manually, thanks!

**Pull request closed without merging**
